# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-02 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(default=None, max_length=60, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('time_of_travel', models.TimeField(default=None, null=True)),
                ('due_date', models.DateField(default=None, null=True)),
                ('request', models.CharField(default=None, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookingCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(default=None, max_length=60, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('time_of_travel', models.TimeField(default=None, null=True)),
                ('due_date', models.DateField(default=None, null=True)),
                ('request', models.CharField(default=None, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30, null=True)),
                ('route', models.CharField(max_length=30, null=True)),
                ('price', models.CharField(max_length=10)),
                ('time', models.TimeField(default=None, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30, null=True)),
                ('route', models.CharField(max_length=30, null=True)),
                ('price', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.AlterField(
            model_name='local',
            name='price',
            field=models.CharField(max_length=10),
        ),
        migrations.AddField(
            model_name='bookingcountry',
            name='company',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Country'),
        ),
        migrations.AddField(
            model_name='bookingcity',
            name='company',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.City'),
        ),
    ]
