# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-02 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20180202_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingcity',
            name='company',
        ),
        migrations.RemoveField(
            model_name='bookingcountry',
            name='company',
        ),
        migrations.AddField(
            model_name='country',
            name='time',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.DeleteModel(
            name='BookingCity',
        ),
        migrations.DeleteModel(
            name='BookingCountry',
        ),
    ]
